### ISSUE TITLE
Port to Gtk4 

### ISSUE THREAD

**Issue by alainm23** [phastmike/vala-circular-progress-bar#6]
Hello again,
I am porting Planner to Gtk4 and ran into a difficulty trying to port this widget. I appreciate your magnificent work, if you could help me with this I would be very grateful.

Greetings.

**Comment by phastmike** [comment]
Hi Alain, I've thought about that already as Gtk is moving forward. I'll take a look at it and let you know about the results. Thanks. All the best and keep up the good work.

**Comment by phastmike** [comment]
Hi @alainm23 just committed a version that works on Gtk4. Can you try it? It can be improved to have the text information (percentage) toggle as you don't use text and it makes sense to be user-defined. Need to add more control on that side.
Anyway, if you don't need you can remove the code below the comment //Textual Information.
The text also adds a dependency in Gtk, --pkg pangocairo. So you probably won't need it if you remove that part of the code.

Check the branch gtk4. I'll merge it with master in the meantime.

Feedback is always welcome ;) 

Thanks

**Comment by alainm23** [comment]
Thank you very much, so far it works perfect for me, thanks for your amazing work.

**Comment by phastmike** [comment]
Hi @alainm23 Thank you for the feedback. Glad it works :) It's a privilege to make this very small contribution to Planner. Keep up the good work. All the very best.
